debug: false

image:
  repository: rancher/rancher-csp-adapter
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  hostNetwork: false

tolerations: []

# at least one csp must be enabled like below
#aws:
#  accountNumber: ""
#  roleName: ""
#  enabled: true
