kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: cattle-system
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: {{ .Chart.Name }}
